### ISSUE TITLE
Conflict: unintentional blocking of a class.

### ISSUE THREAD

**Issue by reklamasieciowa** [decodelabs/exceptional#1]
Hi, I use the library in one of the plugins. Unfortunately, it causes conflicts with other plugins whose classes contain "Exception" in the name. E.g.: Sabberworm\CSS\Parsing\UnexpectedTokenException class.
Is there an option to avoid this? :)

**Comment by betterthanclay** [comment]
Hi - could you explain what's happening or what kind of conflict you're seeing? 

Exceptional is designed to not get in the way of existing code, other classes with "Exception" in the name _shouldn't_ cause a problem..

Do you have an error message you could share?

**Comment by reklamasieciowa** [comment]
I created a Wordpress plugin that uses your solution. I encountered a problem with the performance of another Wordpress plugin in one installation. It turned out that the loadClass method of the AutoLoader classes was blocking the initialization of the seraph_accel\Sabberworm\NParsing\NUnexpectedTokenException class.
I tested an ugly quick fix:
public static function loadClass(
        string $class
    ): void {
        if (
            !preg_match('/\\\\([a-zA-Z0-9_]*)Exception$/', $class) ||
            preg_match('/\\\\UnexpectedTokenException$/', $class) ||
            class_exists($class) ||
            interface_exists($class) ||
            trait_exists($class)
        ) {
            return;
        }

        Factory::create([$class], 1, 'AutoLoader');
    }

**Comment by betterthanclay** [comment]
Thanks - OK, it sounds like the AutoLoader you're using is being registered after the Exceptional loader (which makes sense) - I'll need a little bit of time but I should be able to come up with a solution, I'll let you know when there's something to try.

**Comment by betterthanclay** [comment]
I've just pushed an update (v0.4.5) with a new dependency (DecodeLabs/Wellspring) - this extra library is used to ensure the Exceptional Autoloader is always lower down the spl_autoload queue than normal userspace loaders.

Hopefully that should fix the issue you're having - please give it a try and let me know how it goes.
All you'll need to do is a `composer update`.
